### ISSUE TITLE
Upgrade impl.

### ISSUE THREAD

**Issue by JohnKhandygo** [Eugehabatikov/Eugenii_Samyilov_testing_project_task2#3]
- [x] Могу ошибаться, но по-моему в текущем варианте программа не способна обрабатывать ввод их консоли.
- [x] Не понятно, почему поля класса `unicString` инициализируются только внутри `unicString::loadStrings`. При таком подходе у пользователя остается возможность создать экземпляр класса `unicString` и вызвать сначала любой метод, отличный от `unicString::loadStrings`, что приведем к исключению.
- [x] При вызове `String::subsctring` не проверяется корректность параметра `startIndex`.
- [x] В `unicString::makeUnic` лучше использовать множество (`Set`, надо только выбрать правильную реализацию) для контроля уникальности строк. 
- [x] В `unicString::makeUnic` цикл `while(iterator.hasNext())` можно заменить на [for-each цикл](https://docs.oracle.com/javase/1.5.0/docs/guide/language/foreach.html).

**Comment by Eugehabatikov** [comment]
Добрый день, уважаемый Евгений. 
1) Да, действительно, у меня была ошибка, исправил.
2) Реализовал конструктор класса UniqString , внутри которого вызываю метод  loadString.
3) Добавил проверку.
4) По этому пункту у меня вопрос.
Так как определять уникальность строки необходимо с учетом (или без учета) регистра, и без учета первых s символов я создал класс stringComparator, реализующий интерфейс Comparator. Далее у меня возникла проблема с выбором реализации абстрактного типа данных множества.
в Java доступны три реализации: 
а) HashSet,не подходит нам, т.к. порядок элементов определяется внутренним алгоритмом класса.
b) LinkedHashSet сохраняет порядок добавления элементов (что нам и нужно), но отсутствует возможность использования Comporator'а.
c) ThreeSet позволяет пользоваться Comporator (что нам и нужно), но при этом при выводе элементы сортируются (что нам не нужно).
Соответственно,ни одна реализация нам не подходит. Или я не правильно понял задание? Важен ли нам порядок строк после проверки уникальности? Или проверку уникальности не нужно делать с учетом (без учета) регистра и с отбрасыванием первых s символов?
Я реализовал метод makeUniq с помощью ThreeSet так как он наиболее подходящий ,но оставил реализацию закомментированной.
5) Заменил.

**Comment by Eugehabatikov** [comment]
прошу ,если это возможно ,выдать 3 задание

**Comment by JohnKhandygo** [comment]
- [x] Не понял почему в случае, если `s` больше длины хотя бы одной из сравниваемых строк, выбрасывается исключение. 
- [x] В методе `makeUniq` много копипаста. Одинаковые блоки кода следует обобщать и выносить в отдельные методы.
- [x] Программа работает некорректно в случае одновременного использования флагов `-u` и `-c`.

**Comment by Eugehabatikov** [comment]
Добрый день, уважаемый Евгений.
1) В моей реализации предполагается, что нельзя отбрасывать символов больше чем их в строке. И при попытке выполнить данную операцию пользователем я выбрасываю исключение.
2) исправлено.
3) исправлено.

**Comment by JohnKhandygo** [comment]
> В моей реализации предполагается, что нельзя отбрасывать символов больше чем их в строке.

Вообще вроде бы ничего страшного в этом нет: просто сравниваемая строка в этом случае всегда пуста. Но в принципе как хотите.
